# Generated by Django 5.1.3 on 2024-11-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(max_length=500)),
                ("slug", models.SlugField(unique=True)),
                ("image", models.ImageField(blank=True, upload_to="uploads/")),
            ],
        ),
    ]
