# Generated by Django 5.1.3 on 2024-12-05 20:59

import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "is_personal",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether the user is personal with limited features.",
                        verbose_name="personal",
                    ),
                ),
                (
                    "is_profit",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user is profit with more features.",
                        verbose_name="profit",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "account",
                "verbose_name_plural": "accounts",
                "ordering": ["email"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=12, unique=True)),
                (
                    "city",
                    models.CharField(
                        blank=True, default="Unknown", max_length=100, null=True
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "gender",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            (1, "Female"),
                            (2, "Male"),
                            (3, "Non Binary"),
                            (4, "Gender 4"),
                            (5, "Gender 5"),
                            (6, "Gender 6"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "pronouns",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[(1, "She/Her"), (2, "He/Him"), (3, "They/Them")],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "orientation",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            (1, "Heterosexual"),
                            (2, "Homosexual"),
                            (3, "Bisexual"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "looking_for",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            (1, "Long-Term Relationship"),
                            (2, "Short-Term Relationship"),
                            (3, "Friendship"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "subject",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="subject",
                        serialize=False,
                        to="account.profile",
                    ),
                ),
                (
                    "is_friend",
                    models.BooleanField(default=False, verbose_name="friend"),
                ),
                (
                    "is_following",
                    models.BooleanField(default=False, verbose_name="following"),
                ),
                (
                    "object",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="object",
                        to="account.profile",
                    ),
                ),
            ],
        ),
    ]
