# Generated by Django 5.1.3 on 2024-12-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_account_is_admin_alter_account_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="account",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="account",
            name="last_name",
        ),
        migrations.AlterField(
            model_name="account",
            name="is_organization",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_personal",
            field=models.BooleanField(default=True),
        ),
    ]
